# The Basics

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3], dtype = 'int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])     # double [[...],[...]]
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Dimension
a.ndim
print('Dimension of a = ', a.ndim)

Dimension of a =  1


In [5]:
b.ndim
print('Dimension of b = ', b.ndim)

Dimension of b =  2


In [6]:
# Get Shape
a.shape
print('Shape of a = ', a.shape)
b.shape
print('Shape of b = ', b.shape)     # (2, 3): 2 for horizontal, 3 for vertical

Shape of a =  (3,)
Shape of b =  (2, 3)


In [7]:
# Get Type
a.dtype
print('Type of a is', a.dtype)

Type of a is int32


In [8]:
b.dtype
print('Type of b is', b.dtype)

Type of b is float64


In [9]:
# Get Size
a.itemsize
print('Itemsize =', a.itemsize)

Itemsize = 4


In [10]:
# Get Size
a.size
print('Size =', a.size)     # a.size refers to all array elements

Size = 3


In [11]:
# Get Total Size
a.nbytes
print('Total Size of a =', a.nbytes)
b.nbytes
print('Total Size of b =', b.nbytes)      

# Binary number of 1 is 1
# 'int32' of '1' means that 00000000 00000000 00000000 00000001
# Binary number of 2 is 10
# 'int32' of '2' means that 00000000 00000000 00000000 00000010

# Binary number 9.0
# 'float64' of '9.0' means that 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00001001


Total Size of a = 12
Total Size of b = 48


# Accessing / Changing Specific Elements, Rows, Columns, etc...

In [12]:
m = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(m)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
# Get a specific element [r, c]
m[1, 5]
print(m[1, 5])

13


In [14]:
# Geta Specific row
m[0, :]
print(m[0, :])

[1 2 3 4 5 6 7]


In [15]:
m[1, :]
print(m[1, :])

[ 8  9 10 11 12 13 14]


In [16]:
# Get specific column
m[:, 2]
print(m[:, 2])

[ 3 10]


In [17]:
m[:, 0]
print(m[:, 0])

[1 8]


In [18]:
m[:, 6]
print(m[:, 6])

[ 7 14]


In [19]:
# Getting a little more fancy [rows, startindex: endindex: stepsize]
m[0, 1:-1:2]
print(m[0, 1:-1:2])

[2 4 6]


In [38]:
m[0, 0:6:2]
print(m[0, 0:6:2])

[7 7 7]


In [39]:
m[0, :]
print(m[0, :])

[7 7 7 7 7 7 7]


In [40]:
m[1,5] = 20
print(m)
m[:,2] = [1,2]     # Change array elements on 2-nd column
print(m)
m[:,5] = [95,96]     # Change array elements on 5-nd column, (always remember, count from index 0)
print(m)
m[0,:] = 7     # Change array elements on 0-th row
print(m)
m[1,:] = 8     # Change array elements on 1-st row
print(m)

[[ 7  7  7  7  7  7  7]
 [ 8  8  8  8  8 20  8]]
[[ 7  7  1  7  7  7  7]
 [ 8  8  2  8  8 20  8]]
[[ 7  7  1  7  7 95  7]
 [ 8  8  2  8  8 96  8]]
[[ 7  7  7  7  7  7  7]
 [ 8  8  2  8  8 96  8]]
[[7 7 7 7 7 7 7]
 [8 8 8 8 8 8 8]]


# 3D Array Example

In [41]:
n = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(n)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
# Get specific element (work outside in)
n[0,1,1]
print(n[0,1,1])
n[1,1,1]
print(n[1,1,1])
n[0,0,1]
print(n[0,0,1])
n[1,0,0]
print(n[1,0,0])

4
8
2
5


In [46]:
# Replace
n[:,1,:] = [[3,4],[7,8]]
print(n[:,1,:])

n[:,0,:] = [[7,7],[8,8]]
print(n[:,0,:])

n[:,0] = [[6,6],[5,5]]
print(n[:,0])

n[0,:] = [[6,6]]
print(n[0,:])

n[1,:] = [[11,11],[12,12]]
print(n[1,:])

n[1,:] = [[8,8]]
print(n[1,:])

[[3 4]
 [7 8]]
[[7 7]
 [8 8]]
[[6 6]
 [5 5]]
[[6 6]
 [6 6]]
[[11 11]
 [12 12]]
[[8 8]
 [8 8]]


# Initializing Different Types of Arrays

In [47]:
# All zeros matrix
p = np.zeros((2,3))
print(p)

[[0. 0. 0.]
 [0. 0. 0.]]


In [61]:
# All ones matrix
# ((rows, columns))
p1 = np.ones((4,2,), dtype = 'float64')
print(p1)
print('\n')
# ((numberOfMatrix, rows, columns))
p2 = np.ones((4,2,2), dtype = 'int32')
print(p2)
print('\n')
p3 = np.ones((3,2,2), dtype = 'int32')
print(p3)
print('\n')
p4 = np.ones((5,3,4), dtype = 'int32')
print(p4)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [68]:
# Any other number
q = np.full((2,2), 99, dtype = 'float64')
print(q)

[[99. 99.]
 [99. 99.]]


In [69]:
q1 = np.full((5,5), 1)
print(q1)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [70]:
q2 = np.full((4,2,2), 10)
print(q2)

[[[10 10]
  [10 10]]

 [[10 10]
  [10 10]]

 [[10 10]
  [10 10]]

 [[10 10]
  [10 10]]]


In [71]:
q3 = np.full((5,5,5), 55)
print(q3)

[[[55 55 55 55 55]
  [55 55 55 55 55]
  [55 55 55 55 55]
  [55 55 55 55 55]
  [55 55 55 55 55]]

 [[55 55 55 55 55]
  [55 55 55 55 55]
  [55 55 55 55 55]
  [55 55 55 55 55]
  [55 55 55 55 55]]

 [[55 55 55 55 55]
  [55 55 55 55 55]
  [55 55 55 55 55]
  [55 55 55 55 55]
  [55 55 55 55 55]]

 [[55 55 55 55 55]
  [55 55 55 55 55]
  [55 55 55 55 55]
  [55 55 55 55 55]
  [55 55 55 55 55]]

 [[55 55 55 55 55]
  [55 55 55 55 55]
  [55 55 55 55 55]
  [55 55 55 55 55]
  [55 55 55 55 55]]]


In [72]:
# Any other number (full_like)
q4 = np.full_like(q3, 4)
print(q4)

[[[4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]]

 [[4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]]

 [[4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]]

 [[4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]]

 [[4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]]]


In [84]:
q5 = np.full_like(q4, 100)
print(q5)

[[[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]]

 [[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]]

 [[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]]

 [[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]]

 [[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]]]


In [85]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.18030764, 0.05184703],
       [0.99551855, 0.93083061],
       [0.6431722 , 0.0400725 ],
       [0.58626664, 0.58122025]])

In [86]:
np.random.rand(4,3,3)

array([[[0.41829814, 0.29218202, 0.09956346],
        [0.14588107, 0.68459512, 0.31934183],
        [0.05133739, 0.66461392, 0.19383186]],

       [[0.62896985, 0.95132673, 0.01006384],
        [0.31120097, 0.65396819, 0.23274876],
        [0.20252843, 0.47460171, 0.24963058]],

       [[0.83300194, 0.54633672, 0.46748155],
        [0.49146553, 0.86493788, 0.08414533],
        [0.54000652, 0.73079404, 0.67844316]],

       [[0.32815378, 0.15081336, 0.97879904],
        [0.31097565, 0.37412642, 0.48178871],
        [0.23339592, 0.96780354, 0.0871633 ]]])

In [87]:
r = np.random.rand(5,3,3)
print(r)

[[[0.96857288 0.08240505 0.8830499 ]
  [0.45042209 0.92138356 0.03427103]
  [0.25787004 0.14761775 0.52799416]]

 [[0.41807965 0.82475322 0.27052942]
  [0.36529566 0.43283563 0.24579435]
  [0.4858919  0.89184338 0.8656526 ]]

 [[0.20039122 0.18193197 0.93888094]
  [0.83232165 0.26011844 0.89006246]
  [0.01760196 0.86319187 0.10692032]]

 [[0.54120507 0.06367227 0.5644469 ]
  [0.12373942 0.8165754  0.5096614 ]
  [0.69863934 0.11088823 0.15011714]]

 [[0.80083665 0.54663456 0.05246119]
  [0.04816692 0.93416384 0.10366455]
  [0.28139843 0.50012537 0.72490932]]]


In [90]:
r1 = np.random.random_sample(q5.shape)
print(r1)

[[[0.03378455 0.48830259 0.67023137 0.97215696 0.59465166]
  [0.68941036 0.78710466 0.37571666 0.6472553  0.05901016]
  [0.8718246  0.08894392 0.35349387 0.99927461 0.68359524]
  [0.95906114 0.69767265 0.85014703 0.34884069 0.17661232]
  [0.59754792 0.42190209 0.72345062 0.16339748 0.55410294]]

 [[0.45010163 0.04603336 0.73397926 0.00221435 0.45576447]
  [0.68177646 0.02182888 0.29734341 0.34107722 0.48798802]
  [0.45920618 0.06749613 0.35996747 0.6331036  0.72055075]
  [0.21433785 0.73118101 0.87967812 0.74543636 0.76915627]
  [0.95252082 0.17596246 0.80799732 0.77260748 0.1691875 ]]

 [[0.97372139 0.40228765 0.69637985 0.04601546 0.42776801]
  [0.53058951 0.44680127 0.57509566 0.63789277 0.20191102]
  [0.98268578 0.83287316 0.94327831 0.83010365 0.84713093]
  [0.69409884 0.33714309 0.73516316 0.20655297 0.87370694]
  [0.13687448 0.52893781 0.19550254 0.63388462 0.76190777]]

 [[0.60700377 0.0761232  0.12486604 0.69823712 0.94403839]
  [0.69086351 0.08914882 0.60520463 0.19302257 0.0

In [91]:
r2 = np.random.random_sample(q4.shape)
print(r2)

[[[0.79929372 0.92374761 0.90813189 0.75036234 0.57042164]
  [0.88822194 0.41802957 0.53665195 0.80666449 0.94724729]
  [0.49828109 0.49511062 0.76649101 0.45983849 0.50515564]
  [0.34749789 0.68995839 0.87074721 0.18259192 0.27270885]
  [0.697783   0.25989602 0.3449526  0.18159593 0.42423679]]

 [[0.6121413  0.8997444  0.92894384 0.44544652 0.91342931]
  [0.23931763 0.67576885 0.52214591 0.30427231 0.64279906]
  [0.39437926 0.87497686 0.22855472 0.96697617 0.22169935]
  [0.3668818  0.40529523 0.3820227  0.31625209 0.90092232]
  [0.90493971 0.52163945 0.34495201 0.90811868 0.44053247]]

 [[0.16062741 0.83073194 0.99042131 0.55787338 0.08988636]
  [0.96581456 0.68818896 0.96825603 0.37909353 0.19368045]
  [0.25217342 0.31077323 0.17627463 0.69357194 0.90162218]
  [0.74016677 0.09368966 0.83054439 0.81622993 0.02405392]
  [0.53754316 0.63924188 0.6496366  0.50360537 0.36890823]]

 [[0.93722771 0.05548851 0.2460787  0.15494581 0.59073425]
  [0.38587737 0.76465179 0.83379057 0.93649491 0.6

In [96]:
# Random Integer Value
x = np.random.randint(7, size = (3,3))   # 7 == (0,7) means that random from 0 to 6
print(x)

[[5 4 4]
 [0 5 0]
 [0 2 4]]


In [99]:
x1 = np.random.randint(1,7, size = (4,4))
print(x1)
print('\n')
x2 = np.random.randint(3,8, size = (5,5))
print(x2)

[[2 2 3 3]
 [6 3 1 6]
 [1 3 6 4]
 [3 3 3 5]]


[[6 4 5 5 4]
 [5 5 4 5 4]
 [6 3 5 5 5]
 [7 5 7 4 5]
 [4 7 4 5 7]]


In [100]:
# Identity Matrix
y = np.identity(10)     # ម៉ាទ្រីសឯកតា
print(y)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [101]:
y = np.identity(3)
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [109]:
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3)
print(r1)
print(r1.ndim)
print('\n')
arr = np.array([[4,5,6], [7,8,9]])
r2 = np.repeat(arr, 2, axis = 0)
print(r2)
print(r2.ndim)
print('\n')
arr = np.array([[4,5,6], [7,8,9]])
r2 = np.repeat(arr, 2, axis = 1)
print(r2)
print(r2.ndim)

[1 1 1 2 2 2 3 3 3]
1


[[4 5 6]
 [4 5 6]
 [7 8 9]
 [7 8 9]]
2


[[4 4 5 5 6 6]
 [7 7 8 8 9 9]]
2


In [123]:
output = np.ones((5,5))
print(output)
print('\n')
z = np.zeros((3,3))
z[1,1] = 9
print(z)
print('\n')
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [120]:
n = np.ones((5,5))
n[1:4, 1:4] = 5
print(n)

[[1. 1. 1. 1. 1.]
 [1. 5. 5. 5. 1.]
 [1. 5. 5. 5. 1.]
 [1. 5. 5. 5. 1.]
 [1. 1. 1. 1. 1.]]


In [121]:
x = np.zeros((4,4))
x[1:3, 1:3] = 9
print(x)

[[0. 0. 0. 0.]
 [0. 9. 9. 0.]
 [0. 9. 9. 0.]
 [0. 0. 0. 0.]]


In [137]:
y = np.zeros((6,6))
print(y)

x = np.ones((4,4))
x[1:3, 1:3] = 2
print(x)

y[1:5, 1:5] = x
print(y)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 2. 2. 1.]
 [1. 2. 2. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 2. 2. 1. 0.]
 [0. 1. 2. 2. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [172]:
x = np.zeros((7,7))
print(x)

y = np.ones((5,5))
y[1:4, 1:4] = 2
print(y)

y[2][2] = 3
print(y)

x[1:6, 1:6] = y
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 2. 2. 2. 1.]
 [1. 2. 2. 2. 1.]
 [1. 2. 2. 2. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 2. 2. 2. 1.]
 [1. 2. 3. 2. 1.]
 [1. 2. 2. 2. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 2. 2. 2. 1. 0.]
 [0. 1. 2. 3. 2. 1. 0.]
 [0. 1. 2. 2. 2. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


# Be careful when copying arrays !!!

In [178]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


# Mathematics

In [179]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [182]:
a + 2

array([3, 4, 5, 6, 7])

In [183]:
a - 2

array([-1,  0,  1,  2,  3])

In [184]:
a * 2

array([ 2,  4,  6,  8, 10])

In [185]:
a / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [186]:
a ** 2

array([ 1,  4,  9, 16, 25])

In [188]:
b = np.array([1,0,1,0,1])
a + b

array([2, 2, 4, 4, 6])

In [189]:
a ** 2

array([ 1,  4,  9, 16, 25])

In [191]:
# Take the sin
z = np.sin(a)
print(z)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [192]:
z = np.cos(a)
print(z)

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


# Linear Algebra

In [6]:
a = np.ones((2,4))
print(a)

b = np.full((4,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]
 [2 2]]


array([[8., 8.],
       [8., 8.]])

In [7]:
# Find the determinant
c = np.identity(3)
print(c)
d = np.linalg.det(c)     # Find determinant
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1.0


In [12]:
d = np.identity(6)
d

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [13]:
e = np.linalg.det(d)
print(e)

1.0


In [22]:
f = np.identity(5)
g = np.full((5,5), 9)
print(f * g)
print('\n')
e = np.linalg.det(f * g)     # determinant of matrix (f * g)
print(e)

[[9. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0.]
 [0. 0. 9. 0. 0.]
 [0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 9.]]


59049.00000000008


# Statistics

In [23]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.min(stats)

1

In [25]:
np.max(stats)

6

In [26]:
np.max(stats, axis = 0)

array([4, 5, 6])

In [27]:
np.min(stats, axis = 1)

array([1, 4])

In [28]:
np.min(stats, axis = 0)

array([1, 2, 3])

In [29]:
np.max(stats, axis = 1)

array([3, 6])

In [30]:
np.median(stats, axis = 1)

array([2., 5.])

In [32]:
np.mean(stats)

3.5

In [33]:
np.sum(stats)

21

In [34]:
np.sum(stats, axis = 0)

array([5, 7, 9])

# Reorganizing Arrays

In [46]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)
after = before.reshape((4,2))
print(after)
after = before.reshape((2,2,2))
print(after)
print(after.ndim)
after = before.reshape((1,1,8))
print(after)
print(after.ndim)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
[[[1 2 3 4 5 6 7 8]]]
3


ValueError: cannot reshape array of size 8 into shape (2,2,2,2)