# Miscellaneous
## Loaded Data from File

In [26]:
import numpy as np

In [27]:
# 'Data.txt' File needs to be in same folder as our current coding file
filedata = np.genfromtxt('Data.txt', delimiter = ',', dtype = 'int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [28]:
filedata2 = np.genfromtxt('Data.txt', delimiter = ',', dtype = 'int64')
print(filedata2)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [29]:
# 'Data.txt' File needs to be in same folder as our current coding file
filedata = np.genfromtxt('Data.txt', delimiter = ',')
filedata.astype('int32')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


# Boolean Masking and Advanced Indexing

In [30]:
filedata > 50     # boolean array

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [31]:
filedata[filedata > 50]     # value

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [32]:
## You can index with  a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [33]:
np.any(filedata > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [42]:
np.all(filedata > 50, axis = 1)

array([False, False, False])

In [45]:
(((filedata) > 50 & (filedata < 100)))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True]])