In [1]:
import numpy as np

# Array Vs List

In [6]:
l = [1,2,3]
a = np.array([1,2,3])

l.append(4)
print(l)
# a.append(4)     'can not append in array'
print(a)

[1, 2, 3, 4]
[1 2 3]


In [11]:
l = [1,2,3]
a = np.array([1,2,3])

l = l + [4]
print(l)
a = a + np.array([4])   # becomes ([1+4, 2+4, 3+4]) = ([5 6 7])
print(a)
a = a + np.array([4,4,4])   # same as the following one
print(a)

[1, 2, 3, 4]
[5 6 7]


In [13]:
l = [1,2,3]
a = np.array([1,2,3])

l = l * 2     # In list, if we multiply it by x, so it increases the same elements x time in it too. Like here is an example...
print(l)
a = a * 2     # In NumPy, if we multiply any elements by x, so all elements in that array multiple by x of each element.
print(a)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [15]:
a = np.array([1,2,3])
a = np.sqrt(a)
print(a)

[1.         1.41421356 1.73205081]


In [16]:
a = np.array([1,2,3])
a = np.log(a)
print(a)

[0.         0.69314718 1.09861229]


# Dot Product

In [24]:
l1 = [1,2,3]
l2 = [4,5,6]
a1 = np.array(l1)
a2 = np.array(l2)

# dot product
dot = 0
for i in range(len(l1)):
    dot += l1[i] * l2[i]
print(dot)

32


In [25]:
# dot product using numpy
dot = np.dot(a1, a2)
print(dot)

32


In [26]:
sum1 = a1 * a2
dot = np.sum(sum1)
print(dot)

32


In [27]:
sum1 = a1 * a2
dot = (a1 * a2).sum()
print(dot)

32


In [28]:
sum1 = a1 * a2
dot = sum1.sum()
print(dot)

32


In [29]:
dot = a1 @ a2
print(dot)

32


# Speed Test btw List and NumPy Array

In [34]:
# speed test
from timeit import default_timer as timer

a = np.random.randn(1000)
b = np.random.randn(1000)

A = list(a)
B = list(b)

T = 1000

def dot1():
    dot = 0
    for i in range(len(A)):
        dot += A[i] * B[i]
    return dot

def dot2():
    return np.dot(a,b)

start = timer()
for t in range(T):
    dot1()
end = timer()
t1 = end - start

start = timer()
for t in range(T):
    dot2()
end = timer()
t2 = end - start

print('list calculation', t1)
print('np.dot', t2)
print('ratio', t1/t2)

list calculation 0.23118717799980004
np.dot 0.0018073520000143617
ratio 127.91485997080976


# Indexing and reorganizing arrays

In [35]:
a = np.array([[1,2,6], [3,4,8]])
print(a)

[[1 2 6]
 [3 4 8]]


In [36]:
print(a.shape)

(2, 3)


In [37]:
print(a[:,0])     # all 0-th vertical index

[1 3]


In [38]:
print(a[0,:])     # all 0-th horizontal index

[1 2 6]


In [39]:
print(a.T)     # transpot matrix

[[1 3]
 [2 4]
 [6 8]]


In [40]:
print(np.diag(a))     # digonal matrix

[1 4]


In [45]:
a = np.array([[1,2], [3,4]])
print(np.linalg.det(a))

-2.0000000000000004


In [44]:
c = np.diag(a)
print(np.diag(c))

[[1 0]
 [0 4]]


In [46]:
b = a[0,1]
print(b)

2


In [47]:
b = a[0,:]
print(b)

[1 2]


In [48]:
b = a[1,:]
print(b)

[3 4]


In [49]:
b = a[:,0]
print(b)

[1 3]


In [52]:
b = a[:,1]
print(b)

[2 4]


In [55]:
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a)
b = a[0,1:4]
print(b)

[[1 2 3 4]
 [5 6 7 8]]
[2 3 4]


In [56]:
b = a[1, 0:4]
print(b)

[5 6 7 8]


In [57]:
b = a[-1,-1]
print(b)

8


In [58]:
b = a[-1,-2]
print(b)

7


In [63]:
b = a[-1,-4]
print(b)

5


# Boolean Indexing

In [66]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [68]:
bool_idx = a > 2
print(bool_idx)
print(a[bool_idx])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [69]:
print(a[a > 2])

[3 4 5 6]


In [70]:
b = np.where(a > 2, a, -1)
print(b)

[[-1 -1]
 [ 3  4]
 [ 5  6]]


In [71]:
a = np.array([10,19,30,41,50,61])
print(a)
b = [1,3,5]
print(a[b])

[10 19 30 41 50 61]
[19 41 61]


In [73]:
even = np.argwhere(a % 2 == 0).flatten()
print(a[even])

[10 30 50]


In [79]:
a = np.arange(1,7)
print(a)
print(a.shape)
b = a.reshape((2,3))
print(b)
print(b.shape)
b = a.reshape((3,2))
print(b)
b = a.reshape((6,))
print(b)

[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [83]:
b = a[:, np.newaxis]
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [92]:
a = np.array([[1,2], [3,4]])
print(a)
b = np.array([[5,6]])
print(b)
c = np.concatenate((a,b), axis = None)
print(c)
c = np.concatenate((a,b), axis = 0)
print(c)
c = np.concatenate((a,b.T), axis = 1)
print(c)

[[1 2]
 [3 4]]
[[5 6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


In [94]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

# hstack, vstack
c = np.hstack((a,b))
print(c)
c = np.vstack((a,b))
print(c)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


# Broadcasting

In [95]:
import numpy as np

In [96]:
x = np.array([[1,2,3], [4,5,6], [1,2,3], [4,5,6]])
a = np.array([1,0,1])
y = x + a
print(y)

[[2 2 4]
 [5 5 7]
 [2 2 4]
 [5 5 7]]


In [98]:
a = np.array([[7,8,9,10,11,12,13], [17,18,19,20,21,22,23]])
print(a)

[[ 7  8  9 10 11 12 13]
 [17 18 19 20 21 22 23]]


In [100]:
print(a.sum(axis = None))

210


In [101]:
print(a.sum(axis = 0))     # sum by vertital line

[24 26 28 30 32 34 36]


In [102]:
print(a.sum(axis = 1))     # sum by horizontal line

[ 70 140]


In [104]:
print(a.mean(axis = 1))

[10. 20.]


In [105]:
print(a.mean(axis = None))

15.0


In [106]:
print(a.std(axis = None))
print(np.std(a, axis = None))

5.385164807134504
5.385164807134504


In [107]:
print(a.min(axis = None))
print(a.max(axis = None))

7
23


In [108]:
x = np.array([1,2])
print(x)
print(x.dtype)

[1 2]
int64


In [116]:
x = np.array([1.0,2.0], dtype = 'int64')
print(x)
print(x.dtype)
print('\n')
x = np.array([1.0,2.0], dtype = np.int64)
print(x)
print(x.dtype)
print('\n')
x = np.array([1.0,2.0], dtype = np.int32)
print(x)
print(x.dtype)
print('\n')
x = np.array([1.0,2.0], dtype = np.float64)
print(x)
print(x.dtype)
print('\n')
x = np.array([1.0,2.0], dtype = np.float16)
print(x)
print(x.dtype)
print('\n')
x = np.array([1.0,2.0], dtype = np.float32)
print(x)
print(x.dtype)

[1 2]
int64


[1 2]
int64


[1 2]
int32


[1. 2.]
float64


[1. 2.]
float16


[1. 2.]
float32


In [118]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 42
print(b)
print(a)

[42  2  3]
[1 2 3]


In [119]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [122]:
a = np.ones((2,3))
print(a)
a = np.full((2,3), 5.0)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]
[[5. 5. 5.]
 [5. 5. 5.]]


In [124]:
# Identity matrix
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [125]:
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [126]:
a = np.linspace(0,10,5)      # Start-Stop-Step
print(a)

[ 0.   2.5  5.   7.5 10. ]


# Random Number

In [128]:
a = np.random.random((3,3))   # Uniform distribution btw 0-1
print(a)     # mean = 1 and var = 0

[[0.39168926 0.89877411 0.33717907]
 [0.27606186 0.38439448 0.73359781]
 [0.43549536 0.69116858 0.71583402]]


In [130]:
a = np.random.randn(1000)     # Gaussian/Normal distribution btw 0-1
print(a.mean(), a.var())

0.032184209672916 0.9665737359546868


In [133]:
a = np.random.randint(3,10, size = (3,3))
print(a)
a = np.random.randint(10, size = (3,3))
print(a)

[[3 3 9]
 [3 6 5]
 [6 4 7]]
[[8 5 4]
 [0 3 0]
 [8 9 4]]


In [134]:
a = np.random.choice(5, size = 10)
print(a)

[0 3 0 4 3 4 1 1 0 3]


In [135]:
a = np.random.choice([-8,-7,-6], size = 10)
print(a)

[-8 -6 -7 -7 -6 -7 -7 -7 -6 -6]


# Linear Algebra (Eigenvalues / Solving Linear Systems)

In [138]:
a = np.array([[1,2], [3,4]])
eigenvalues, eigenvectors = np.linalg.eig(a)
print(eigenvalues)
print(eigenvectors)   # column vector

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [146]:
# e_vec * e_val = A * e_vec
b = eigenvectors[:,0] * eigenvalues[0]
print(b)
b = a @ eigenvectors[:,0]
print(b)

[ 0.30697009 -0.21062466]
[ 0.30697009 -0.21062466]


In [150]:
b = eigenvectors[:,0] * eigenvalues[0]
print(b)
c = a @ eigenvectors[:,0]
print(b)
print(b == c)     # This is not the correct way to compare 2 arrays
print(np.allclose(b,c))    # Compare 2 array

[ 0.30697009 -0.21062466]
[ 0.30697009 -0.21062466]
[ True False]
True


In [154]:
# Exercise Solving
A = np.array([[1,1], [1.5,4.0]])
b = np.array([2200, 5050])

x = np.linalg.inv(A).dot(b)
print(x)

x = np.linalg.solve(A, b)
print(x)

[1500.  700.]
[1500.  700.]


# Loading CSV Files

In [156]:
# np.loadtxt, np.genfromtxt
data = np.loadtxt('Data.txt', delimiter = ',', dtype = np.float32)
print(data)
print(data.shape)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
(3, 18)


In [157]:
data = np.genfromtxt('Data.txt', delimiter = ',', dtype = np.float32)
print(data)
print(data.shape)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
(3, 18)
